### PR TITLE
Release v3.11-r1

### PR DESCRIPTION
**Pull request by lucaboesch**

### CODE REVIEW

**Comment by abias** [comment]
Hi @lucaboesch ,

thank you very much for this PR which adds Moodle 3.11 support!

I have just approved the Github Action runs (which need to be approved by a Github repo maintainer when a first-time contributor submits a PR) and expect that they will finish soon with a 'all green' status.

Regarding the code, this looks nearly spot-on!

I have just spotted one minor glitch:
The Changelog entry for the change of https://github.com/moodleuulm/moodle-availability_role/pull/13/commits/8a1dc2156251f329756d3475826f428a1ee061db is part of the https://github.com/moodleuulm/moodle-availability_role/pull/13/commits/2975b4f9ebeeaed38d2521d5b9b4b00ff0f2274b commit.

We can ignore that glitch, but it would be awesome if you could fix that if it is possible for you in reasonable time.
Please tell me how you want to proceed.

Cheers,
Alex

**Comment by lucaboesch** [comment]
Dear @abias
I fixed the changelog entries so each one contains only its own changes.
It would be great if you could continue merging in order to sometimes being able to release r3.11-1.
Best,
Luca

**Review by abias — APPROVED** [review]
Dear Luca,

this PR is spot-on. Thank you very much for this contribution!

Please note that the MariaDB checks aren't passing currently. This is not related to your PR, this is a problem with moodle-plugin-ci currently. See https://tracker.moodle.org/browse/MDL-72131 and https://github.com/moodlehq/moodle-local_codechecker/pull/149 for details.

I will update the Github Actions / moodle-plugin-ci configuration in the repo here once the fix has been released in moodle-plugin-ci.

Cheers,
Alex

**Comment by lucaboesch** [comment]
Version has been released.

**Pull request closed without merging**
